### ISSUE TITLE
Unchecked message pushing results in publish failure

### ISSUE THREAD

**Issue by robborden** [Coinigy/PureSocketCluster#2]
If I try to publish messages in a loop like this:

```
foreach (var obj in objList) 
{
     _scSocket.Push("TICKER",obj);
}
```

only the first obj/message ever reaches the SocketCluster server.  Subsequent messages are not published.  I finally found that all messages are published properly if I publish like this:

```
foreach (var obj in objList)
{
     _scSocket.Push("TICKER",obj);
     await Task.Delay(10);
}
```

**Comment by ByronAP** [comment]
is this still an issue?
