### ISSUE TITLE
Cant call Ticker

### ISSUE THREAD

**Issue by freezepro** [Coinigy/PureSocketCluster#4]
Could you please provide how to call properly(TICKER) also receive All Markets?

Doing this: 
  var cn = _scc.CreateChannel("TICKER").Subscribe();
            cn.OnMessage(TradeData);
or this 
  var cn0 = _scc.CreateChannel("TICKER-BTRX--ETH--BTC").Subscribe();
            cn0.OnMessage(TradeData);

but it doesn't work

**Comment by michaelvolz** [comment]
The WebSocket TICKER is deprecated. 
The only feasable way for me was to access the Ticker via the REST API. But you only get one at a time, at least as far as I know. 

Source: [CryptoTicker Updated + ‘TICKER’ Websocket Channel to be Deprecated](https://blog.coinigy.com/2017/07/cryptoticker-updated-ticker-websocket-channel-to-be-deprecated/)

**Comment by robborden** [comment]
Although the ticker channel is deprecated, you can still get your favorite tickers delivered over websocket.  You can read more here: https://blog.coinigy.com/2017/07/cryptoticker-updated-ticker-websocket-channel-to-be-deprecated/

**Comment by michaelvolz** [comment]
@robborden I tried the websocket way but was only able to get a handful. If I wanted all of them, it did not work. Is this by design or a bug? Or do I miss some information? I searched a while and found nothing.
