### ISSUE TITLE
PureSocketClusterSocket() Constructors dont compile.

### ISSUE THREAD

**Issue by junkomatic** [Coinigy/PureSocketCluster#6]
The constructors in this class try to pass requestHeader: Tuple<string, string> into the constructor for PureWebSocket, but these constructors require a **List** of <Tuple<string, string>> parameter! These errors make it not compile. Easy enough to fix by creating the list vars and adding them in.

Otherwise, nice project!

**Comment by ByronAP** [comment]
Yeah just haven't gotten around to fixing that last release, will do it today, thanks for the reminder

**Comment by ByronAP** [comment]
Completed with version 2.0.1
