### ISSUE TITLE
Operation is not supported on this platform. Xamarin Forms iOS

### ISSUE THREAD

**Issue by kevinvella** [Coinigy/PureSocketCluster#8]
Hi,

I was trying the PureSocketCluster library. Internally it uses Utf8Json. When i run it on iOS it gives me an Operation is not supported on this platform.

Running it on Xamarin.Android it works very well.

Versions:
Utf8Json - v1.3.7
Xamarin Forms - v2.5.1.444934
PureSocketCluster - v2.0.1

Hope this can help
Attaching some screenshots of the stack trace
![screen shot 2018-04-27 at 10 40 16](https://user-images.githubusercontent.com/15779395/39355091-89fa499c-4a0c-11e8-93a7-bc059b957107.png)
![screen shot 2018-04-27 at 10 40 09](https://user-images.githubusercontent.com/15779395/39355093-8a1a884c-4a0c-11e8-9cb0-074afb4f419f.png)
![screen shot 2018-04-27 at 10 40 02](https://user-images.githubusercontent.com/15779395/39355094-8a379432-4a0c-11e8-9013-0d604e6d4657.png)
![screen shot 2018-04-27 at 10 39 55](https://user-images.githubusercontent.com/15779395/39355095-8a54e212-4a0c-11e8-935f-1f6741f2f9ef.png)
![screen shot 2018-04-27 at 10 39 48](https://user-images.githubusercontent.com/15779395/39355096-8a738564-4a0c-11e8-9cbd-8bf18d3272c4.png)
![screen shot 2018-04-27 at 10 39 41](https://user-images.githubusercontent.com/15779395/39355097-8a95b972-4a0c-11e8-833a-02620d6bbe4b.png)
![screen shot 2018-04-27 at 10 39 35](https://user-images.githubusercontent.com/15779395/39355098-8ab74f24-4a0c-11e8-9cbc-046a0d0bde33.png)

**Comment by ByronAP** [comment]
thank you, I will check on this with the utf8lib

**Comment by ByronAP** [comment]
I will externalize the de/serializer interface to allow modifications

**Comment by ByronAP** [comment]
but for anyone else that comes across this  you just need to dynamically map a resolver

https://github.com/neuecc/Utf8Json/issues/74#issuecomment-384957937

**Comment by ByronAP** [comment]
closed in V2.0.2
